name: mongo-connect-local

services:
  mongo1:
    image: mongo:7.0.40
    command: ["mongod","--port","28017","--replSet","rs-local","--bind_ip_all","--oplogSize","256"]
    healthcheck:
      test: ["CMD", "mongosh", "--port", "28017", "--quiet", "--eval", "quit(db.adminCommand('ping').ok ? 0 : 1)"]
      interval: 5s
      timeout: 3s
      retries: 20
    ports: ["127.0.0.1:28017:28017"]
    volumes: ["mongo1:/data/db"]
    networks: [mongo-lab]
  mongo2:
    image: mongo:7.0.40
    command: ["mongod","--port","28018","--replSet","rs-local","--bind_ip_all","--oplogSize","256"]
    healthcheck:
      test: ["CMD", "mongosh", "--port", "28018", "--quiet", "--eval", "quit(db.adminCommand('ping').ok ? 0 : 1)"]
      interval: 5s
      timeout: 3s
      retries: 20
    ports: ["127.0.0.1:28018:28018"]
    volumes: ["mongo2:/data/db"]
    networks: [mongo-lab]
  mongo3:
    image: mongo:7.0.40
    command: ["mongod","--port","28019","--replSet","rs-local","--bind_ip_all","--oplogSize","256"]
    healthcheck:
      test: ["CMD", "mongosh", "--port", "28019", "--quiet", "--eval", "quit(db.adminCommand('ping').ok ? 0 : 1)"]
      interval: 5s
      timeout: 3s
      retries: 20
    ports: ["127.0.0.1:28019:28019"]
    volumes: ["mongo3:/data/db"]
    networks: [mongo-lab]
networks:
  mongo-lab: {}
volumes:
  mongo1: {}
  mongo2: {}
  mongo3: {}
